service: manda-ai-online
frameworkVersion: '3'

provider:
  name: aws
  region: us-east-1
  runtime: nodejs14.x
  profile: ismaelash-sls

functions:
  graphql:
    handler: graphql.graphqlHandler
    events:
    - http:
        path: /
        method: post
        cors: true
    - http:
        path: /
        method: get
        cors: true

plugins:
  - serverless-dotenv-plugin

package:
  patterns:
    - '!node_modules/.prisma/client/libquery_engine-*'
    - 'node_modules/.prisma/client/libquery_engine-rhel-*'
    - '!node_modules/prisma/libquery_engine-*'
    - '!node_modules/@prisma/engines/**'